= Cheatsheets

[[VertxHawkularOptions]]
== VertxHawkularOptions

++++
 Vert.x Hawkular monitoring configuration.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchDelay]]`batchDelay`|`Number (int)`|
+++
Set the maximum delay between two consecutive batches (in seconds).
+++
|[[batchSize]]`batchSize`|`Number (int)`|
+++
Set the maximum number of metrics in a batch.
+++
|[[enabled]]`enabled`|`Boolean`|-
|[[host]]`host`|`String`|
+++
Set the Hawkular Metrics service host.
+++
|[[httpOptions]]`httpOptions`|`link:dataobjects.html#HttpClientOptions[HttpClientOptions]`|
+++
Set the configuration of the Hawkular Metrics HTTP client.
+++
|[[metricsServiceUri]]`metricsServiceUri`|`String`|
+++
Set the Hawkular Metrics service URI.
+++
|[[port]]`port`|`Number (int)`|
+++
Set the Hawkular Metrics service port.
+++
|[[prefix]]`prefix`|`String`|
+++
Set the metric name prefix.
+++
|[[schedule]]`schedule`|`Number (int)`|
+++
Set the metric collection interval (in seconds).
+++
|[[tenant]]`tenant`|`String`|
+++
Set the Hawkular tenant.
+++
|===

